language: php

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: nightly
        - php: hhvm-3.6
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.15
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
    fast_finish: true
    allow_failures:
        - php: 7.1
        - php: nightly
        - php: hhvm-nightly

before_install: phpenv config-rm xdebug.ini || true
install: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --ignore-platform-reqs
script: vendor/bin/peridot specs

cache:
    directories:
        - $HOME/.composer

sudo: false
